### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by JStiles9552** [JStiles9552/CLIM_680_Assignment_2#1]
If I could improve my 12-month plot, I would like to remove the data from the maps that is shown in Canada. Since my project is focused on the Northeast U.S., I would like to remove data that is shown outside of this region, but I am not sure how to remove it.

**Comment by pdirmeyer** [comment]
This is certainly doable, but it would take a bit of work. There are several ways to it - they fall into two categories: (1) masking or removing (setting to NaN) the data over Canada in your dataset; (2) overlaying a polygon to hide the data over Canada. If you ultimately want to do calculations on irregular areas (e.g., specific states, or US only), then (1) is the best option ([examples of data needed to do this](https://psl.noaa.gov/data/usclimdivs/boundaries.html), and then you can use a python package such as [regionmask](https://regionmask.readthedocs.io/en/stable/)).  Otherwise, hiding data also requires defining the right polygons - [here's one fancy example](https://stackoverflow.com/questions/62448828/python-cartopy-map-clip-area-outside-country-polygon).

**Comment by pdirmeyer** [comment]
Reilly, you can close this issue.
